init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd BuildApp
  - cmd: build.cmd UnitTests
  - cmd: build.cmd ConventionTests
  - cmd: build.cmd CreatePackages
test: off
nuget:
  account_feed: true
  project_feed: true
artifacts:
- path: '**\octokit*.nupkg'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/octokit-test/api/v2/package
  api_key:
    secure: 9ydM6g6KP4SSZmMQV5PE++3tlLBH3wTTMyO2GBgr2F1st/YNG3ZdGTWZ96FA7kqa
  skip_symbols: true
  artifact: 'packaging\octokit*.nupkg'
  on:
    branch: release
    APPVEYOR_REPO_TAG: true